### ISSUE TITLE
Design - Profile Card

### ISSUE THREAD

**Issue by Jason2426** [lemuelmgsn/your-tribe-for-life-profile-card#5]
# Kleurgebruik Tip

Voor het design van je visitekaartje zou je standaard donkere kleuren kunnen gebruiken wat er dan waarschijnlijk al veel vetter uit ziet. Verder ziet het er inderdaad straightforward en slick uit gj gangy.

**Comment by lemuelmgsn** [comment]
thx voor de tip gang. 

[Screenshot van donker design](https://private-user-images.githubusercontent.com/144004180/369192804-0dae5a92-8773-49ae-b4ff-99e7c595ae56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzUwNTQsIm5iZiI6MTcyNjgzNDc1NCwicGF0aCI6Ii8xNDQwMDQxODAvMzY5MTkyODA0LTBkYWU1YTkyLTg3NzMtNDlhZS1iNGZmLTk5ZTdjNTk1YWU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMjE5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2U4ZDNiOWRhMzE3YzkwMDA2ZDFjYjcwMzQ5MDNmMmYwNDU1NmY3MDE2NDAzNDM4MWNkZDc4NjRlNGViMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.31YlhV2_wc7LbqHXg2yFG7rBld_kitTDxrxgWGDFsmo)
