### ISSUE TITLE
Onnodige map 'visitekaartje'?

### ISSUE THREAD

**Issue by Jason2426** [lemuelmgsn/your-tribe-for-life-profile-card#6]
https://github.com/lemuelmgsn/your-tribe-for-life-profile-card/tree/main/visitekaartje

Ik zag dat je een map 'visitekaartje' in je repo hebt die waarschijnlijk onnodig is dus deze kun je deleten bro.

**Comment by lemuelmgsn** [comment]
verwijderd broski.

https://github.com/fdnd-task/your-tribe-for-life-profile-card/commit/f438267f97728e3b2e4f0001b9152032364116e3
